import json
import random
import datetime
import copy
from pathlib import Path

# Source file for JSON elements
SOURCE_FILE = "bronch_extractions_patched/bronch_notes_part_001.json"
OUTPUT_DIR = "Synthetic_expansions"

def generate_random_date(start_year, end_year):
    start = datetime.date(start_year, 1, 1)
    end = datetime.date(end_year, 12, 31)
    return start + (end - start) * random.random()

def get_variations():
    """
    Returns a dictionary of text variations.
    Structure: Note_Index (0-4) -> Style_Index (1-9) -> Text
    """
    variations = {
        0: { # Note 0: Malignant Central Airway Obstruction (Therapeutic Aspiration + BAL)
            1: "Procedure: Therapeutic Bronchoscopy.\nActions:\n- LMA placed.\n- Inspection: Y-stent in place. Significant mucus plugging (Right > Left > Trachea).\n- RUL partially obstructed by SEMS tip.\n- LUL tumor (40%) noted, not treated.\n- Intervention: Mucus removed via suction, forceps, and bicarb instillation. Stents recanalized.\n- BAL: LUL anterior segment (40cc in/30cc out).\n- No bleeding.\nPlan: PACU.",
            2: "OPERATIVE REPORT\n\nINDICATION: The patient presented with airway stent occlusion secondary to malignant central airway obstruction.\n\nPROCEDURE: Following the induction of general anesthesia, a therapeutic flexible bronchoscope was introduced via a laryngeal mask airway. Inspection of the tracheobronchial tree revealed the indwelling silicone Y-stent to be structurally intact. However, substantial inspissated secretions were observed, causing varying degrees of obstruction within the tracheal and bronchial limbs. The right mainstem metallic stent was also noted to be impacted. A systematic debridement was undertaken utilizing mechanical disruption with the bronchoscope tip, extraction forceps, and mucolytic lavage with sodium bicarbonate. This resulted in the restoration of patency to the stented airways. Additionally, a targeted bronchoalveolar lavage was performed in the anterior segment of the left upper lobe for microbiological assessment. The patient tolerated the procedure without immediate sequelae.",
            3: "Service: Bronchoscopy with Therapeutic Aspiration (31645) and Bronchoalveolar Lavage (31624).\n\nProcedure Details:\n1. Therapeutic Aspiration (31645): The primary intent of the procedure was the clearance of the tracheobronchial tree. Significant mucous plugging was identified obstructing the existing silicone Y-stent and right mainstem SEMS. Clearance was achieved using forceps debulking and therapeutic suctioning facilitated by sodium bicarbonate. This constitutes initial therapeutic aspiration.\n2. Bronchoalveolar Lavage (31624): A separate diagnostic BAL was performed in the LUL anterior segment (distinct from the stent clearing zones). 40cc sterile saline instilled; 30cc effluent collected and sent for analysis.",
            4: "Procedure Note\nAttending: Dr. [Name]\nResident: [Name]\n\nProcedure: Therapeutic Bronchoscopy\n\nSteps:\n1. Time out performed.\n2. General anesthesia induced. LMA placed.\n3. Scope inserted. Y-stent visualized.\n4. Findings: Thick mucus obstructing stents. RUL stent tip noted.\n5. Action: Aggressive suctioning and forceps removal of mucus plugs. Bicarb used.\n6. Stents cleared.\n7. Mini-BAL performed in LUL anterior segment.\n8. Scope removed. Patient stable.",
            5: "Procedure bronchoscopy pt has malignant airway obstruction and the stents are clogged up. used general anesthesia and LMA. looked down and saw the y stent and the metal one in the right side they were full of thick dry mucous. The RUL is kinda blocked by the stent but no pneumonia seen. LUL has a tumor but we left it alone. spent a long time cleaning out the mucous with forceps and bicarb and the scope tip. finally got it open. did a bal in the LUL anterior seg just to check. no bleeding really. sent to pacu.",
            6: "The procedure was performed in the bronchoscopy suite. After administration of sedatives an LMA was inserted and the therapeutic flexible bronchoscope was passed through the vocal cords and into the trachea. The patients known Silicone Y-stent was well positioned. There was signifigant thich dry mucous with mild obstruction of the tracheal limb, moderate obstruction of the left bronchial limb and significant obstruction of the right bronchial limb and the telescoping right mainstem covered metallic stent. The right upper lobe was partially obstructed by the distal tip of the SEM but there was no evidence of post-obstructive pneumonia and all right sided segmental airways were patent without endobronchial disease. On the left the distal mainstem, lower lobe bronchi were patient without evidence of endobronchial disease. At the anterior aspect of the left upper lobe takeoff there was partially obstructive endobronchial tumor causing approximately 40% reduction in caliber which did not warrant treatment at this time. Through a combination of mechanical debulking with the bronchoscope tip, forceps debulking and use of sodium bicarbonate instillation the adhesive mucous was slowly removed, with near complete recanalization of the stents. Subsequently a mini BAL was performed in the anterior segment of the left upper lobe with 40cc instillation and 30cc return. At this point inspection was performed to evaluate for any bleeding or other complications and none was seen. The bronchoscope was removed and the procedure was completed.",
            7: "[Indication]\nAirway stent occlusion in setting of malignant central airway obstruction.\n\n[Anesthesia]\nGeneral Anesthesia via LMA.\n\n[Description]\nTherapeutic scope passed. Silicone Y-stent and RMS covered stent identified. Significant obstruction via inspissated mucus plugs. Mechanical and forceps debulking performed along with sodium bicarbonate lavage until stents recanalized. LUL anterior segment tumor noted (40%). Diagnostic BAL performed in LUL anterior segment.\n\n[Plan]\nTransfer to PACU. Discharge when stable.",
            8: "The patient was brought to the bronchoscopy suite for management of airway stent occlusion. Under general anesthesia, we inserted an LMA and advanced the therapeutic bronchoscope. The silicone Y-stent was in good position, but the limbs were heavily obstructed by thick, dry mucus, particularly on the right side involving the metallic stent. We proceeded to clear these obstructions using a combination of mechanical disruption, forceps removal, and sodium bicarbonate instillation. This successfully recanalized the stents. We also noted a tumor at the LUL takeoff but decided against intervention at this time. Finally, we performed a mini-BAL in the left upper lobe anterior segment before concluding the procedure.",
            9: "PREOPERATIVE DIAGNOSIS: Malignant Central Airway Obstruction \nPOSTOPERATIVE DIAGNOSIS: Same\nINDICATIONS: Airway stent blockage \nSedation: General Anesthesia\nDESCRIPTION: The intervention was carried out in the bronchoscopy suite. After sedation, an LMA was placed and the therapeutic flexible bronchoscope was navigated through the vocal cords. The patient's Silicone Y-stent was seated correctly. There was substantial inspissated secretions with mild blockage of the tracheal limb, moderate blockage of the left bronchial limb and significant blockage of the right bronchial limb and the telescoping right mainstem covered metallic stent. The right upper lobe was partially blocked by the distal tip of the SEM but there was no sign of post-obstructive pneumonia. Through a combination of mechanical clearance with the bronchoscope tip, forceps extraction and use of sodium bicarbonate instillation the adhesive mucous was eliminated, with near complete reopening of the stents. Subsequently a mini lavage was conducted in the anterior segment of the left upper lobe. No bleeding was observed."
        },
        1: { # Note 1: Navigational Bronchoscopy + EBUS (RLL Nodule)
            1: "Procedure: Nav Bronch + EBUS.\nIndication: RLL nodule.\nActions:\n- Airway inspection: Normal.\n- Navigation: SuperDimension to RLL superior segment.\n- Confirmation: Radial EBUS (concentric).\n- Biopsy: Needle and forceps. ROSE: Malignant.\n- EBUS Staging: Stations 4L (7 passes), 7 (5 passes), 4R (4 passes).\n- Bleeding at 4R stopped with cold saline.\n- Extubated. Stable.",
            2: "OPERATIVE NARRATIVE: The patient was brought to the operative theater for diagnostic bronchoscopy regarding a right lower lobe pulmonary nodule. Following the induction of general anesthesia and intubation with an 8.5 mm endotracheal tube, the T190 video bronchoscope was utilized to survey the airway, which appeared anatomically normal. Electromagnetic navigation (SuperDimension) guided the extended working channel to the target lesion in the superior segment of the right lower lobe. Radial endobronchial ultrasound confirmed a concentric, heterogeneous signal. Transbronchial biopsies were obtained via needle and forceps; rapid on-site evaluation was consistent with malignancy. Subsequently, a linear endobronchial ultrasound (EBUS) scope was deployed for mediastinal staging. Stations 4L, 7, and 4R were systematically sampled via transbronchial needle aspiration. Hemostasis at station 4R was achieved with topical iced saline.",
            3: "CPT Coding Substantiation:\n- 31627 (Navigation): Computer-assisted image guidance (SuperDimension) was utilized to navigate to the RLL superior segment lesion.\n- 31654 (Peripheral EBUS): Radial EBUS probe used to confirm lesion location prior to biopsy.\n- 31628 (TBLB): Transbronchial biopsies (forceps) taken from the RLL single lobe.\n- 31653 (EBUS-TBNA): Real-time EBUS guidance used to sample 3 distinct mediastinal stations: 4L, 7, and 4R. (Supports >2 stations code).",
            4: "Procedure Note\n\nIndication: Lung Nodule\nAnesthesia: GA\n\nProcedure Steps:\n1. Intubated 8.5 ETT.\n2. White light bronchoscopy: Normal anatomy.\n3. ENB (SuperDimension) to RLL superior segment.\n4. REBUS confirmation (concentric).\n5. Needle and Forceps biopsies obtained. ROSE positive.\n6. Switch to EBUS scope.\n7. Sampled 4L, 7, 4R.\n8. Hemostasis achieved at 4R with ice saline.\n\nComplications: None.",
            5: "we did a nav bronch and ebus today for a lung nodule pt was asleep general anesthesia tube size 8.5 first we looked around everything looked normal then we used the superdimension thing to go to the RLL superior segment where the nodule was radial ultrasound showed it was concentric so we stuck it with the needle and the forceps ROSE said cancer. Then we switched to the big ultrasound scope and sampled nodes 4L 7 and 4R ROSE said lymphocytes ok. 4R bled a little bit so we put some ice water on it and it stopped no other issues thanks.",
            6: "Procedure Name: Navigational Bronchoscopy and Staging EBUS. Indications: Diagnosis and staging of presumed lung cancer. Pre-operative diagnosis: Pulmonary Nodule. Post-operative Diagnosis: Pulmonary Nodule. Medications: General Anesthesia. Consent was obtained from the patient prior to procedure after explanation in lay terms the indications, details of procedure, and potential risks and alternatives. All questions were answered and informed consent was documented as per institutional protocol. A history and physical were performed and updated in the pre-procedure assessment record. Laboratory studies and radiographs were reviewed. A time-out was performed prior to the intervention. Following intravenous medications as per the record and topical anesthesia to the upper airway and tracheobronchial tree, the T190 video bronchoscope was introduced through the mouth, via an 8.5 ETT  and advanced to the tracheobronchial tree. The distal trachea was of normal caliber. The carina was sharp. The tracheobronchial tree was examined to at least the first subsegmental level. Bronchial mucosa and anatomy were normal; there are no endobronchial lesions. The Covidien superDimension locatable guide was then inserted through the working channel and registration was performed. The Edge 180 degree extended working channel was then attached to the bronchoscope.  Using navigational map we advanced the catheter into the proximity of the lesion within the superior segment of the right lower lobe. Confirmation of placement once at the point of interest with radial ultrasound showed a diffuse heterogeneric concentric view within the lesion consistent with the known part solid nodule. Biopsies were then performed with peripheral needle under fluoroscopic visualization with ROSE findings consistent with malignancy, additional forceps biopsies were then performed in the same location. The flexible bronchoscope was then removed and the UC180F convex probe EBUS bronchoscope was introduced via the ETT. A systematic hilar and mediastinal lymph node survey was carried out. Sampling criteria (5mm short axis diameter) were met in station 4L, 7 and 4R lymph nodes. Sampling by transbronchial needle aspiration was performed with the Olympus EBUS TBNA 22- and 25-gauge needles beginning with the 4L Lymph node (7 biopsies), followed by the 7 lymph node (5 biopsies) and finally the 4R lymph node (4 biopsies). ROSE evaluation was consistent with adequate lymph node sampling in all stations. All samples were sent for routine cytology. Following completion of EBUS bronchoscopy, the T190 video bronchoscope was then re-inserted. Active oozing was noted at the site of the 4R lymph node and topical iced saline was applied with subsequent resolution of the bleeding and after suctioning remaining  blood and secretions there was no evidence of active bleeding and the bronchoscope was subsequently removed.",
            7: "[Indication]\nDiagnosis and staging of RLL pulmonary nodule.\n\n[Anesthesia]\nGeneral, 8.5 ETT.\n\n[Description]\n1. Diagnostic Bronchoscopy: Normal airways.\n2. Navigation: SuperDimension to RLL superior segment.\n3. Confirmation: Radial EBUS (concentric).\n4. Sampling: Transbronchial needle and forceps biopsies. ROSE: Malignancy.\n5. EBUS Staging: Stations 4L, 7, 4R sampled via TBNA.\n6. Hemostasis: Iced saline used for oozing at 4R.\n\n[Plan]\nRepeat CXR tomorrow. Await pathology.",
            8: "The patient underwent a navigational bronchoscopy and EBUS staging for a presumed lung cancer. After inducing general anesthesia and placing an 8.5 ETT, we inspected the airways and found no endobronchial lesions. We utilized the SuperDimension navigation system to reach the target in the RLL superior segment, confirming position with radial ultrasound. We took biopsies using both a needle and forceps; preliminary results suggest malignancy. We then switched to the EBUS scope and sampled lymph nodes at stations 4L, 7, and 4R. There was some minor bleeding at the 4R site which we stopped with iced saline. The patient was stable throughout.",
            9: "Procedure Name: Guided Bronchoscopy and Staging EBUS\nIndications: Identification and staging of presumed lung cancer\nMedications: General Anesthesia\nFollowing intravenous medications and topical anesthesia, the video bronchoscope was inserted via an 8.5 ETT. The tracheobronchial tree was assessed. Anatomy was normal. The navigational guide was then inserted and registration was executed. Using the navigational map we advanced the catheter into the proximity of the lesion within the superior segment of the right lower lobe. Validation of placement with radial ultrasound showed a concentric view consistent with the nodule. Samples were then obtained with peripheral needle under fluoroscopic visualization with ROSE findings consistent with malignancy, additional forceps samples were then taken in the same location. \nThe flexible bronchoscope was then withdrawn and the convex probe EBUS bronchoscope was introduced. A systematic hilar and mediastinal lymph node survey was carried out. Sampling by transbronchial needle aspiration was performed beginning with the 4L Lymph node, followed by the 7 lymph node and finally the 4R lymph node. ROSE evaluation was consistent with adequate lymph node sampling in all stations. Active oozing was noted at the site of the 4R lymph node and topical iced saline was applied with subsequent resolution."
        },
        2: { # Note 2: Bilateral Lung Masses (RUL Endobronchial + LLL Peripheral)
            1: "Indication: Bilateral masses.\nAirway: 8.5 ETT, GA.\nFindings:\n- RUL: Endobronchial fungating mass. Obstructs Superior/Anterior segs.\n- LLL: Peripheral lesion Superior seg.\nProcedures:\n- RUL Mass: TBNA (5 passes) + Forceps (6 samples). Bleeding controlled (epi).\n- LLL Lesion: Radial EBUS (concentric). TBNA (4 passes) + Forceps (5 samples). Bleeding controlled (epi).\n- BAL: LLL Superior seg (110cc).\nROSE: RUL=Malignant. LLL=Necrosis.\nPlan: PACU.",
            2: "OPERATIVE REPORT\nINDICATION: Bilateral pulmonary opacities suspicious for malignancy.\nPROCEDURE: Following general anesthesia (8.5 ETT), flexible bronchoscopy revealed an endobronchial fungating mass obstructing the right upper lobe (RUL) superior and anterior segments. This was sampled via transbronchial needle aspiration (TBNA) and endobronchial forceps biopsy; hemostasis was achieved with epinephrine. Attention was turned to the left lower lobe (LLL), where a peripheral lesion in the superior segment was localized via radial EBUS (concentric view). This was sampled via TBNA and transbronchial forceps biopsy. A bronchoalveolar lavage (BAL) was also performed in the LLL superior segment for microbiologic analysis. Preliminary evaluation (ROSE) confirmed malignancy in the RUL and necrosis in the LLL.",
            3: "CPT Justification:\n- 31629 (TBNA): Performed on the initial RUL mass (5 passes).\n- 31628 (TBLB): Transbronchial biopsy performed on the separate LLL lesion (5 samples) in a different lobe.\n- 31654 (Radial EBUS): Utilized to locate the peripheral LLL lesion prior to biopsy.\n- 31624 (BAL): Performed in the LLL superior segment (Note: Bundled if not distinct pathology, but performed for micro).\nNote: Separate lesions in separate lobes treated.",
            4: "Resident Note\nPatient: [Name]\nDx: Bilateral lung masses\n\nProcedure:\n1. GA / 8.5 ETT.\n2. RUL: Found fungating mass. Biopsied with needle and forceps. (ROSE: CA).\n3. LLL: Used Radial EBUS to find nodule in superior segment. Biopsied with needle and forceps. (ROSE: Necrosis).\n4. BAL LLL done.\n5. Epinephrine used for bleeding at both sites.\n6. Stable.",
            5: "Bronchoscopy for bilateral lung masses patient under general with an 8.5 tube. RUL had a big fungating mass blocking the segments so we biopsied it with needle and forceps bleeding a bit used epi. ROSE said cancer. Then went to the LLL used the radial ultrasound to find the spot in the superior segment. Biopsied that too needle and forceps. ROSE just showed necrosis. Did a lavage there too. Patient fine no issues.",
            6: "Findings: The flexible bronchoscope was introduced through the 8.5 ETT and advanced into the trachea. The trachea was thoroughly examined, revealing a sharp carina. The bronchial tree was inspected bilaterally to the subsegmental level. Inspection notable for an endobronchial fungating mass in the RUL obstructing the superior and anterior segments. The remaining airways appeared normal with no additional endobronchial abnormalities, mucosal irregularities, or abnormal secretions. Tissue Sampling Procedures A. Right Upper Lobe (RUL) Endobronchial Biopsy An endobronchial mass was identified obstructing the superior and anterior segments of the RUL. Sampling Techniques: Transbronchial Needle Aspiration (TBNA): Performed using Periview Flex transbronchial needle with five (5) passes. Endobronchial Forceps Biopsy: Performed with six (6) samples obtained. Hemostasis: Moderate bleeding noted, successfully controlled with instillation of 2 cc of topical epinephrine. B. Left Lower Lobe (LLL) Lesion Biopsy A second lesion was identified in the superior segment of the LLL using radial endobronchial ultrasound (EBUS) with a concentric view. Sampling Techniques: Transbronchial Needle Aspiration (TBNA): Performed using Periview Flex with four (4) passes. Transbronchial Forceps Biopsy: Performed with five (5) samples obtained. Hemostasis: Moderate bleeding noted, successfully controlled with instillation of 2 cc of topical epinephrine. C. Bronchoalveolar Lavage (BAL) - Left Lower Lobe (LLL) Superior Segment A BAL was performed in the superior segment of the left lower lobe. Instillation: 110 cc normal saline Return: 20 cc Samples sent for cytology, microbiology (bacterial, fungal, and mycobacterial cultures), and differential cell count. D. Rapid On-Site Evaluation (ROSE) Right Upper Lobe (RUL) lesion: ROSE interpretation was malignant. Left Lower Lobe (LLL) lesion: ROSE revealed abundant necrosis but pathology was unable to definitively confirm malignancy.",
            7: "[Indication]\nBilateral lung masses.\n\n[Anesthesia]\nGeneral, 8.5 ETT.\n\n[Description]\n1. RUL: Fungating endobronchial mass found. Biopsied (TBNA x5, Forceps x6). Epinephrine used for hemostasis. ROSE: Malignant.\n2. LLL: Peripheral lesion localized with Radial EBUS. Biopsied (TBNA x4, Forceps x5). Epinephrine used. ROSE: Necrosis.\n3. BAL: LLL Superior segment performed.\n\n[Plan]\nAwait final pathology. CXR post-op.",
            8: "The patient presented with bilateral lung masses. Under general anesthesia, we performed a bronchoscopy. In the Right Upper Lobe, we found a fungating mass obstructing the airway. We took multiple biopsies using a needle and forceps; preliminary results suggest cancer. We controlled some bleeding with epinephrine. We then moved to the Left Lower Lobe, where we used radial ultrasound to find a peripheral lesion. We biopsied this as well, though the rapid check only showed dead tissue (necrosis). We also washed the area (BAL) to check for infection. The patient tolerated the procedure well.",
            9: "Anesthesia/Medications:\n\u2022\tGeneral anesthesia with 8.5 ETT placement\n\u2022\tTopical anesthesia- 6cc 1% lidocaine)\n\u2022\tAdditional intravenous medications per institutional protocol\nIndications:\nBilateral lung masses \nPre-Procedure Diagnosis: Suspected lung  malignancy\nPost-Procedure Diagnosis: Suspected lung  malignancy\nFindings:\n\u2022\tThe flexible bronchoscope was introduced through the 8.5 ETT and advanced into the trachea.\n\u2022\tThe trachea was thoroughly examined, revealing a sharp carina.\n\u2022\tThe bronchial tree was inspected bilaterally to the subsegmental level.\n\u2022\tInspection notable for an endobronchial fungating mass in the RUL blocking the superior and anterior segments.\n\u2022\tThe remaining airways appeared normal.\nA. Right Upper Lobe (RUL) Endobronchial Sampling\n\u2022\tAn endobronchial mass was identified obstructing the superior and anterior segments of the RUL.\n\u2022\tSampling Techniques:\no\tTransbronchial Needle Aspiration (TBNA): Performed using Periview Flex transbronchial needle with five (5) passes.\no\tEndobronchial Forceps Sampling: Performed with six (6) samples obtained.\no\tHemostasis: Moderate bleeding noted, successfully controlled with instillation of 2 cc of topical epinephrine.\nB. Left Lower Lobe (LLL) Lesion Sampling\n\u2022\tA second lesion was identified in the superior segment of the LLL using radial endobronchial ultrasound (EBUS) with a concentric view.\n\u2022\tSampling Techniques:\no\tTransbronchial Needle Aspiration (TBNA): Performed using Periview Flex with four (4) passes.\no\tTransbronchial Forceps Sampling: Performed with five (5) samples obtained.\no\tHemostasis: Moderate bleeding noted, successfully controlled with instillation of 2 cc of topical epinephrine.\nC. Bronchoalveolar Lavage (BAL) - Left Lower Lobe (LLL) Superior Segment\n\u2022\tA BAL was performed in the superior segment of the left lower lobe."
        },
        3: { # Note 3: RLL Endobronchial Lesion + EBUS Station 7
            1: "Indication: RLL mass.\nAnesthesia: General.\nProcedure:\n- White light bronch: Endobronchial lesion RLL superior segment.\n- Forceps biopsy x multiple. Cold saline/epi/lidocaine for bleeding.\n- ROSE: ?Malignancy.\n- EBUS: Stations 11L, 10L, 7, 4R, 10R, 11R visualized.\n- Station 7 (>5mm) sampled (TBNA x4).\n- ROSE: Adequate.\nComplications: None.",
            2: "OPERATIVE REPORT\n\nINDICATION: Right lower lobe mass.\n\nPROCEDURE: The patient was placed under general anesthesia. Diagnostic bronchoscopy revealed an endobronchial lesion within the superior segment of the right lower lobe (RLL). Multiple forceps biopsies were obtained. Hemostasis was secured using topical epinephrine and cold saline. Rapid on-site evaluation (ROSE) suggested malignancy. Subsequently, endobronchial ultrasound (EBUS) was performed for staging. Lymph node station 7 met sampling criteria (>5mm) and was aspirated four times. ROSE confirmed specimen adequacy. The patient tolerated the procedure without complication.",
            3: "CPT Codes:\n- 31625: Bronchoscopy with endobronchial biopsy (RLL superior segment lesion).\n- 31652: Bronchoscopy with EBUS sampling of 1-2 mediastinal/hilar stations (Station 7 sampled).\nNote: Bleeding management (epi/saline) included in primary procedure.",
            4: "Procedure Note\nPatient: [Name]\nIndication: RLL Mass\n\nSteps:\n1. Anesthesia induced.\n2. Bronchoscope inserted.\n3. Found lesion in RLL superior segment.\n4. Biopsied with forceps.\n5. Controlled bleeding.\n6. Switched to EBUS scope.\n7. Looked at nodes: 11L, 10L, 7, 4R, 10R, 11R.\n8. Sampled Station 7 (4 passes).\n\nPlan: Follow pathology.",
            5: "Patient here for RLL mass under general anesthesia. Bronchoscopy showed a lesion in the RLL superior segment so we biopsied it with forceps a bunch of times. Bleeding stopped with cold saline and epi. ROSE said maybe cancer. Then did EBUS looked at a lot of nodes but only station 7 was big enough to poke so we did 4 passes. ROSE said it was good. All done no complications.",
            6: "ANESTHESIA:  General. INDICATIONS FOR PROCEDURE: Right lower lobe mass. DESCRIPTION OF PROCEDURE: Explanation of the procedure and all risks, benefits, and options were discussed. The risks include but were not limited to bleeding, infection, and pneumothorax. All questions were answered. The patient was anesthetized with topical anesthesia and the bronchoscope was introduced through the mouth where topical lidocaine was instilled on the vocal cords and into the trachea. When adequate anesthesia was achieved, the bronchoscope was passed through the vocal cords and topical lidocaine administered on a local-regional fashion. The endobronchial tree was inspected and patient was found to have endobronchial lesion noted in the right lower lobe superior segment.  Multiple forceps biopsies were obtained at this time.  Lidocaine with epinephrine was instilled in addition to cold saline to achieve adequate hemostasis. ROSE at bedside confirmed adequate sample and possible evidence of malignancy.  The bronchoscope was then slowly withdrawn and removed. The endobronchial ultrasound bronchoscope was inserted through the vocal cords.  Staging ultrasound performed.  Measured on ultrasound the 11 L, 10 L, for now, 7, 4R, 10 R, 11RS and 11Ri.  Station 7 was greater than 5 mm and therefore was sampled by needle aspiration x4.  ROSE at bedside confirmed adequate sample.  Bronchoscope was slowly withdrawn and removed. Diagnostic bronchoscope passed through the vocal cords.  Tracheobronchial tree was examined adequate hemostasis was achieved.  Right lower lobe superior segment endobronchial lesion no longer bleeding.  Bronchoscope was slowly withdrawn and removed.",
            7: "[Indication]\nRight lower lobe mass.\n\n[Anesthesia]\nGeneral.\n\n[Description]\n1. Inspection: Endobronchial lesion RLL superior segment.\n2. Biopsy: Endobronchial forceps biopsies taken. Hemostasis with epi/cold saline.\n3. EBUS: Stations 11L, 10L, 7, 4R, 10R, 11R assessed.\n4. Sampling: Station 7 sampled (TBNA x4).\n\n[Plan]\nFollow pathology. Notify patient.",
            8: "The patient presented with an RLL mass. We performed a bronchoscopy under general anesthesia. Upon inspection, we found a lesion inside the airway of the right lower lobe's superior segment. We took several biopsies with forceps and used epinephrine and cold saline to stop the bleeding. The rapid test suggested it might be cancer. We then used the ultrasound scope (EBUS) to check the lymph nodes. Station 7 was enlarged, so we sampled it with a needle four times. The procedure went well with no complications.",
            9: "ANESTHESIA:  General\nINDICATIONS: Right lower lobe mass\nDESCRIPTION: Explanation of the procedure and all risks, benefits, and options were discussed. The risks include but were not limited to bleeding, infection, and pneumothorax. All questions were answered. \nThe patient was anesthetized with topical anesthesia and the bronchoscope was introduced through the mouth where topical lidocaine was instilled on the vocal cords and into the trachea. When adequate anesthesia was achieved, the bronchoscope was passed through the vocal cords and topical lidocaine administered on a local-regional fashion. The endobronchial tree was assessed and patient was found to have endobronchial lesion noted in the right lower lobe superior segment.  Multiple forceps samples were obtained at this time.  Lidocaine with epinephrine was instilled in addition to cold saline to achieve adequate hemostasis. ROSE at bedside confirmed adequate sample and possible evidence of malignancy.  The bronchoscope was then slowly withdrawn and removed.\nThe endobronchial ultrasound bronchoscope was inserted through the vocal cords.  Staging ultrasound performed.  Measured on ultrasound the 11 L, 10 L, for now, 7, 4R, 10 R, 11RS and 11Ri.  Station 7 was greater than 5 mm and therefore was sampled by needle aspiration x4.  ROSE at bedside confirmed adequate sample."
        },
        4: { # Note 4: CF Patient, Cavitary Lesion (Mycetoma)
            1: "Indication: CF, RLL cavitary lesion.\nAnesthesia: General, ETT.\nFindings: RUL apical/posterior fusion. RLL superior segment purulence. Cavity visualized with mycetoma.\nProcedures:\n- BAL RLL superior segment (60cc in/20cc out).\n- Forceps biopsy of intracavitary mass.\nComplications: Moderate bleeding. Controlled with epi, iced saline, wedge.\nPlan: PACU. Admit.",
            2: "OPERATIVE SUMMARY: The patient, a 56-year-old male with cystic fibrosis, presented for evaluation of an RLL cavitary lesion. Under general anesthesia, a P190 hybrid bronchoscope was advanced. Inspection revealed purulent secretions emanating from the RLL superior segment. A bronchoalveolar lavage (BAL) was performed. Visualization of the segment revealed a cavity containing a fungal ball (mycetoma). Multiple forceps biopsies were obtained from this mass. The procedure was complicated by moderate hemorrhage, which was successfully arrested using 4cc epinephrine, 30cc iced saline, and segmental wedging. The patient was extubated and transferred to PACU.",
            3: "CPT Justification:\n- 31628 (Transbronchial Biopsy): Forceps biopsies taken from the mass within the RLL cavity. (Primary service).\n- 31624 (BAL): Separate bronchoalveolar lavage performed in the RLL superior segment to collect fluid for extensive culture (AFB, fungal, cytology). \nNote: Bleeding management is bundled.",
            4: "Procedure Note\nPatient: Timothy Grace, 56M\nDx: CF, RLL cavity\n\nSteps:\n1. GA / ETT.\n2. Inspection: RUL anomalies. RLL sup seg purulence.\n3. BAL performed RLL sup seg.\n4. Visualization: Cavity with fungus ball seen.\n5. Biopsy: Forceps biopsies of mass.\n6. Complication: Moderate bleeding. Stopped with epi/ice/wedge.\n\nPlan: Cultures pending. CXR.",
            5: "Cystic fibrosis patient with a cavity in the right lower lobe. put him to sleep general anesthesia. went down with the hybrid scope. Saw pus coming from the RLL superior seg. Did a BAL there. Saw a cavity with a fungus ball inside. Biopsied it with forceps. It bled a moderate amount so we used epinephrine and ice water and wedged the scope until it stopped. Extubated fine sent to recovery.",
            6: "INDICATION FOR OPERATION:  This is a 56 year old-year-old male with cystic fibrosis who presents with a cavitary lesion in right lower lobe.  The nature, purpose, risks, benefits and alternatives to Bronchoscopy were discussed with the patient in detail.  Patient indicated a wish to proceed with surgery and informed consent was signed. PREOPERATIVE DIAGNOSIS: R91.1 Solitary Lung Nodule POSTOPERATIVE DIAGNOSIS:  R91.1 Solitary Lung Nodule ANESTHESIA: General Anesthesia MONITORING : Pulse oximetry, heart rate, telemetry, and BP were continuously monitored by an independent trained observer that was present throughout the entire procedure. INSTRUMENT : Flexible Hybrid (Pediatric) Bronchoscope ESTIMATED BLOOD LOSS:   Moderate COMPLICATIONS:    None PROCEDURE IN DETAIL: After successful induction of anesthesia, a timeout was performed to confirm the patient’s identity, the procedure, and the location. Following administration of intravenous medications and topical anesthesia to the upper airway, a P190 hybrid video bronchoscope was introduced through the endotracheal tube. The trachea appeared normal. The bronchoscope was advanced to the main carina, which was noted to have a sharp angle. The scope was then directed into the left mainstem bronchus, allowing visualization of all segments and subsegments of the left upper lobe, lingula, and lower lobe; no abnormalities were identified on the left side. The bronchoscope was withdrawn to the trachea and advanced into the right mainstem bronchus. All segments and subsegments of the right upper, middle, and lower lobes were examined. Purulent material was observed emanating from the superior segment of the right lower lobe. The bronchoscope was wedged in this segment, and a bronchoalveolar lavage was performed using 60 cc of instilled saline, yielding 20 cc of return fluid. During the lavage, a cavity was visualized in the superior segment of the right lower lobe containing a well-demarcated soft tissue mass with a granular texture, consistent with a mycetoma. The right airway anatomy was notable for fusion of the apical and posterior segments in the right upper lobe; aside from the cavity, no additional masses or lesions were identified. After thorough inspection, multiple forceps biopsies were obtained from the mass within the cavity. Moderate bleeding ensued and was effectively managed with 4 cc of epinephrine, 30 cc of iced saline, and wedging of the scope in the affected segment, which successfully controlled the hemorrhage. The bronchoscope was removed, and the procedure was completed without further incident.",
            7: "[Indication]\nCF patient, RLL cavitary lesion.\n\n[Anesthesia]\nGeneral.\n\n[Description]\n1. Inspection: RLL superior segment purulence.\n2. BAL: 60cc instilled, 20cc return.\n3. Findings: Cavity with mycetoma visualized.\n4. Biopsy: Forceps biopsies of mass.\n5. Complication: Moderate bleeding controlled with epi/ice/wedge.\n\n[Plan]\nCXR. Cultures pending.",
            8: "Mr. Grace, a cystic fibrosis patient, underwent bronchoscopy for an RLL cavity. We used general anesthesia and a hybrid scope. We found pus coming from the RLL superior segment and performed a wash (BAL). Looking deeper, we found a cavity with a fungal ball inside. We took biopsies of this mass. It started bleeding moderately, so we used epinephrine, iced saline, and wedged the scope to stop it. He recovered well.",
            9: "INDICATION FOR OPERATION:  This is a 56 year old-year-old male with cystic fibrosis who presents with a cavitary lesion in right lower lobe.  The nature, purpose, risks, benefits and alternatives to Bronchoscopy were discussed with the patient in detail.  Patient indicated a wish to proceed with surgery and informed consent was signed.\nPROCEDURE IN DETAIL:\nFollowing administration of intravenous medications and topical anesthesia to the upper airway, a P190 hybrid video bronchoscope was introduced through the endotracheal tube. The trachea appeared normal. The bronchoscope was advanced to the main carina, which was noted to have a sharp angle. The scope was then directed into the left mainstem bronchus, allowing visualization of all segments and subsegments of the left upper lobe, lingula, and lower lobe; no abnormalities were identified on the left side. The bronchoscope was withdrawn to the trachea and advanced into the right mainstem bronchus. All segments and subsegments of the right upper, middle, and lower lobes were examined. Purulent material was observed emanating from the superior segment of the right lower lobe. The bronchoscope was wedged in this segment, and a bronchoalveolar lavage was performed using 60 cc of instilled saline, yielding 20 cc of return fluid. During the lavage, a cavity was visualized in the superior segment of the right lower lobe containing a well-demarcated soft tissue mass with a granular texture, consistent with a mycetoma. The right airway anatomy was notable for fusion of the apical and posterior segments in the right upper lobe; aside from the cavity, no additional masses or lesions were identified. After thorough inspection, multiple forceps samples were obtained from the mass within the cavity. Moderate bleeding ensued and was effectively managed with 4 cc of epinephrine, 30 cc of iced saline, and wedging of the scope in the affected segment, which successfully controlled the hemorrhage."
        }
    }
    return variations

def get_base_data_mocks():
    """
    Returns mock data for the 5 notes in bronch_notes_part_001.json.
    Assigns random names/ages where "UNKNOWN" exists.
    """
    return [
        {"idx": 0, "orig_name": "John Doe", "orig_age": 65, "names": ["John Smith", "Michael Brown", "Robert Jones", "William Davis", "David Wilson", "Richard Evans", "Charles Thomas", "Joseph Roberts", "Thomas White"]},
        {"idx": 1, "orig_name": "Jane Doe", "orig_age": 60, "names": ["Mary Johnson", "Patricia Williams", "Linda Brown", "Barbara Miller", "Elizabeth Davis", "Jennifer Garcia", "Maria Rodriguez", "Susan Wilson", "Margaret Martinez"]},
        {"idx": 2, "orig_name": "Robert Roe", "orig_age": 70, "names": ["James Anderson", "John Taylor", "Robert Moore", "Michael Jackson", "William Martin", "David Lee", "Richard Perez", "Charles Thompson", "Joseph White"]},
        {"idx": 3, "orig_name": "Alice Poe", "orig_age": 55, "names": ["Sarah Harris", "Karen Clark", "Nancy Lewis", "Lisa Robinson", "Betty Walker", "Dorothy Young", "Sandra Allen", "Ashley King", "Kimberly Wright"]},
        {"idx": 4, "orig_name": "Timothy Grace", "orig_age": 56, "names": ["Timothy Grace", "George Scott", "Kenneth Green", "Steven Baker", "Edward Adams", "Brian Nelson", "Ronald Hill", "Anthony Campbell", "Kevin Mitchell"]}
    ]

def main():
    # Load original data from source file
    try:
        with open(SOURCE_FILE, 'r', encoding='utf-8') as f:
            source_data = json.load(f)
    except FileNotFoundError:
        print(f"Error: Source file not found: {SOURCE_FILE}")
        print("Please ensure the file exists or update SOURCE_FILE path.")
        return
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in source file: {e}")
        return
    
    if not isinstance(source_data, list):
        print(f"Error: Source file must contain a JSON array, got {type(source_data)}")
        return
    
    print(f"Loaded {len(source_data)} notes from {SOURCE_FILE}")
    
    variations_text = get_variations()
    base_data = get_base_data_mocks()
    
    # Ensure output directory exists
    output_dir = Path(OUTPUT_DIR)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    generated_notes = []
    
    # Iterate through each original note in source data
    for idx, original_note in enumerate(source_data):
        if idx >= len(base_data):
            print(f"Warning: More notes in source than base_data entries. Skipping note {idx}.")
            continue
            
        record = base_data[idx]
        orig_age = record['orig_age']
        
        # Iterate through the 9 styles
        for style_num in range(1, 10):
            
            # Deep copy the original note structure
            note_entry = copy.deepcopy(original_note)
            
            # Determine new random age (+/- 3 years)
            new_age = orig_age + random.randint(-3, 3)
            
            # Determine new random date (within 2025)
            rand_date_obj = generate_random_date(2025, 2025)
            rand_date_str = rand_date_obj.strftime("%Y-%m-%d")
            
            # Get the specific name assigned
            new_name = record['names'][style_num - 1]
            
            # Update note_text with the variation
            if idx in variations_text and style_num in variations_text[idx]:
                note_entry["note_text"] = variations_text[idx][style_num]
            else:
                # Fallback if variation is missing (should not happen with complete dictionary)
                print(f"Warning: Missing variation for Note {idx}, Style {style_num}")
                continue

            # Update registry_entry fields if they exist
            if "registry_entry" in note_entry:
                # Update Age
                if "patient_demographics" in note_entry["registry_entry"]:
                    if note_entry["registry_entry"]["patient_demographics"] is None:
                         note_entry["registry_entry"]["patient_demographics"] = {}
                    note_entry["registry_entry"]["patient_demographics"]["age_years"] = new_age
                elif "patient_age" in note_entry["registry_entry"]: # Handle schema variation if any
                     note_entry["registry_entry"]["patient_age"] = new_age

                # Update Date
                note_entry["registry_entry"]["procedure_date"] = rand_date_str
                
                # Update Patient Name/MRN to make it unique
                # Since source MRNs are mostly "UNKNOWN", we set a synthetic one
                note_entry["registry_entry"]["patient_mrn"] = f"SYN_BRONCH_{idx+1}_{style_num}"
                
            # Add metadata about the synthetic generation
            note_entry["synthetic_metadata"] = {
                "source_file": SOURCE_FILE,
                "original_index": idx,
                "style_type": style_num,
                "generated_name": new_name,
                "generation_date": datetime.datetime.now().isoformat()
            }
            
            generated_notes.append(note_entry)

    # Output to JSON in Synthetic_expansions folder
    output_filename = output_dir / "synthetic_bronch_notes_part_001.json"
    with open(output_filename, 'w', encoding='utf-8') as f:
        json.dump(generated_notes, f, indent=2, ensure_ascii=False)
    
    print(f"Successfully generated {len(generated_notes)} synthetic notes in {output_filename}")

if __name__ == "__main__":
    main()
